name: Build and Test Workflow

on:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0'

    - name: Restore dependencies
      run: dotnet restore YourMobileGuide.sln

    - name: Build the project
      run: dotnet build YourMobileGuide.sln --configuration Release --no-restore
      continue-on-error: true

    - name: Create Test Results Directory
      run: mkdir -p $GITHUB_WORKSPACE/testresults

    - name: Run unit tests
      run: |
        dotnet test UnitTests/UnitTests.csproj --no-build --results-directory $GITHUB_WORKSPACE/testresults --logger "trx;LogFileName=unit_test_results.trx"
      continue-on-error: true

    - name: Upload Unit Test Results
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: unit-test-results
        path: $GITHUB_WORKSPACE/testresults

    - name: Run UI tests
      run: dotnet test UITest/UITest.csproj --no-build --logger "trx;LogFileName=ui_test_results.trx"
      continue-on-error: true

    - name: Send Email Notification
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: smtp.office365.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: Build and Test Status
        body: |
          Did Build Succeed: ${{ needs.build-and-test.result == 'success' }}
          Did Tests Pass: ${{ needs.build-and-test.result == 'success' }}
        to: aabraham2@seattleu.edu
        from: knalla@seattleu.edu
        use_tls: true
